apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calculator-dev

bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: karash121/calculator:latest   # ← your image
    target:
      kind: Deployment
      name: calculator